
# Week 1, Introduction

### Feelings and expectations

How am I feeling? Currently I'm a bit exhausted with all the technical challenges I had with Git and Rstudio integration with several computers. After installing brand new Linux system things were going better though.  

So the course started with  

* problems  
* troubles  
* challenges

...but from this on I'm expecting

* easiness
* joy
* wisdom.

I expect to learn R and Git integration, _and already did_. Looking forward to hear ideas for some **data analysis**: I have experience with another software and R packages as well, but with R it's sometimes difficult to see which packages and techniques are supposed or recommended to be used in specific tasks. Also it is interesting to see how approach in data science and conventional statistics differs.  

I heard about this course when Kimmo was advertising it via Statnet mailing list.  

### R calculations...  

```{r}
1+1
0/0
```
### ...and inline code.  

Square root of two i.e. $\sqrt 2$ equals `r sqrt(2)`.

### My GithHub repository:  

[https://github.com/irual/IODS-project](https://github.com/irual/IODS-project)
